[package]
name = "kernel"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
arrow = { version = "2.0.0", features = ["simd"] }
num = "0.3"
ast = { path = "../ast" }
twox-hash = "1.6.0"