[workspace]
members = [
    "src/ast",
    # "src/benchmarks",
    "src/catalog",
    "src/encoding",
    # "src/execute",
    "src/kernel",
    "src/parser",
    "src/planner",
    "src/storage",
    "src/zetasql",
    "src/zetasql_build",
]