[workspace]
members = [
    "src/ast",
    "src/catalog",
    "src/encoding",
    "src/execute",
    "src/kernel",
    "src/parser",
    "src/planner",
    "src/scratch",
    "src/storage",
    "src/zetasql",
]