[workspace]
members = [
    "ast",
    "benchmarks",
    "catalog",
    "encoding",
    "execute",
    "kernel",
    "parser",
    "planner",
    "sketch",
    "storage",
    "zetasql",
    "zetasql_build",
]