[workspace]
members = [
    "ast",
    "benchmarks",
    "catalog",
    "coordinator",
    "e2e_tests",
    "encoding",
    "execute",
    "kernel",
    "parser",
    "planner",
    "rpc",
    "remote_execution",
    "sequences",
    "statistics",
    "storage",
    "worker",
    "zetasql",
]