[workspace]
members = [
    "ast",
    "benchmarks",
    "catalog",
    "context",
    "coordinator",
    "encoding",
    "execute",
    "kernel",
    "parser",
    "planner",
    "protos",
    "remote_execution",
    "statistics",
    "storage",
    "worker",
    "zetasql",
    "zetasql_build",
]