[package]
name = "ast"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
arrow = "2.0.0"
chrono = { version = "0.4.11", features = ["serde"] }
zetasql = { path = "../zetasql" }