[package]
name = "catalog"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
arrow = { version = "2.0.0", features = ["simd"] }
ast = { path = "../ast" }
zetasql = { path = "../zetasql" }