[package]
name = "remote_execution"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.3.1"
futures = "0.3.13"
tokio = { version = "1.5.0", features = ["rt"] }
tonic = "0.4.3"
prost = "0.7.0"
prost-types = "0.7.0"
regex = "1.4.2"

ast = { path = "../ast" }
context = { path = "../context" }
kernel = { path = "../kernel" }
protos = { path = "../protos" }
statistics = { path = "../statistics" }