[package]
name = "zetasql"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"
doctest = false

[dependencies]
futures = { version = "0.3.13", features = [] }
prost = "0.7.0"
prost-types = "0.7.0"
tonic = "0.4.3"

[build-dependencies]
tonic-build = "0.4.2"