[package]
name = "catalog"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
ast = { path = "../ast" }
kernel = { path = "../kernel" }
log = { path = "../log" }
remote_execution = { path = "../remote_execution" }
zetasql = { path = "../zetasql" }