mod bootstrap;
mod catalog;
mod defaults;

/// The root catalag is the unnamed parent of every other catalog.
pub const ROOT_CATALOG_ID: i64 = 0;

/// The metadata catalog is bootstrapped.
/// Every other catalog is generated by querying the metadata catalog,
/// but the metadata catalog *itself* must be pre-defined.
pub const METADATA_CATALOG_ID: i64 = 1;

/// The first 100 ids are reserved for the bootstrap schema.
pub const RESERVED_IDS: i64 = 100;

pub use crate::{catalog::*, defaults::*};
