[package]
name = "protos"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.3.1"
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.4.0"
kernel = { path = "../kernel" }

[build-dependencies]
tonic-build = { version = "0.4.0", features = ["prost"] }
prost-build = "0.7.0"