[package]
name = "protos"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.3.1"
futures = "0.3.13"
grpcio = { version = "0.8.2", features = ["prost-codec"]}
once_cell = "1.5.2"
prost = "0.7.0"
prost-types = "0.7.0"

kernel = { path = "../kernel" }

[build-dependencies]
grpcio-compiler = { version = "0.8.0", features = ["prost-codec"]}