[package]
name = "protos"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
prost = "0.7"
prost-types = "0.7"
tonic = "0.4.0"

[build-dependencies]
tonic-build = { version = "0.4.0", features = ["prost"] }