[package]
name = "parser"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[[bin]]
name = "client"
path = "client.rs"

[dependencies]
futures = "0.3.4"
tokio = { version = "0.2", features = ["macros"] }
tonic = "0.1.1"
zetasql = { path = "../zetasql" }