[package]
name = "planner"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
arrow = "2.0.0"
ast = { path = "../ast" }
encoding = { path = "../encoding" }
fixtures = { path = "../fixtures" }
parser = { path = "../parser" }
regex = "1"
zetasql = { path = "../zetasql" }