[package]
name = "planner"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
regex = "1.4.2"
chrono = "0.4.11"
rand = "0.7.3"
ast = { path = "../ast" }
catalog = { path = "../catalog" }
context = { path = "../context" }
encoding = { path = "../encoding" }
kernel = { path = "../kernel" }
parser = { path = "../parser" }
statistics = { path = "../statistics" }
storage = { path = "../storage" }
zetasql = { path = "../zetasql" }