steps:
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Build Tests'
    entrypoint: sh
    args: [-c, $_BUILD_TESTS]
    env: 
      - RUSTFLAGS=-Z instrument-coverage
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Run Tests'
    entrypoint: sh
    args: [-c, $_RUN_TESTS]
    env: 
      - RUSTFLAGS=-Z instrument-coverage
      - COORDINATOR=http://127.0.0.1:50100
      - WORKER_0=http://127.0.0.1:50101
      - WORKER_COUNT=1
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Build Benchmarks'
    entrypoint: sh
    args: [-c, $_BUILD_BENCHMARKS]
  - name: gcr.io/cloud-builders/gsutil
    id: 'Restore Benchmarks Timing'
    entrypoint: sh
    args: [-c, 'gsutil cp gs://zeedb-build-cache/criterion-main-${_RELEASE}.zip criterion.zip && unzip criterion.zip -d / || true']
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Run Benchmarks'
    entrypoint: sh
    args: [-c, $_RUN_BENCHMARKS]
  - name: gcr.io/cloud-builders/gsutil
    id: 'Save Benchmarks Timing'
    entrypoint: sh
    args: [-c, "find /cargo/target/criterion -name '*.json' | zip criterion.zip -@ && gsutil cp criterion.zip 'gs://zeedb-build-cache/criterion-${BRANCH_NAME}-${_DEVELOP}.zip'"]
artifacts:
  objects:
    location: gs://zeedb-build-artifacts
    paths:
      - cargo-timing-test.html
      - cargo-timing-bench.html
      - coverage.tar.gz
      - benchmarks.tar.gz
substitutions: 
  _RELEASE: '1'
  _DEVELOP: '1'
  _BUILD_TESTS: |
    set -eux
    cargo build -Z timings --tests --bins
    sccache --show-stats
    mv cargo-timing.html cargo-timing-test.html
  _RUN_TESTS: |
    set -eux
    zetasql_server &
    COORDINATOR_PORT=50100 /cargo/target/debug/zeedb-coordinator &
    WORKER_PORT=50101 WORKER_ID=0 /cargo/target/debug/zeedb-worker &
    cargo test
    grcov . --binary-path /cargo/target/debug/ -s . -t html --branch --ignore-not-existing -o ./coverage
    tar -zcf coverage.tar.gz ./coverage
  _BUILD_BENCHMARKS: |
    set -eux
    cargo bench -Z timings --no-run
    sccache --show-stats
    mv cargo-timing.html cargo-timing-bench.html
  _RUN_BENCHMARKS: |
    set -eux
    zetasql_server & 
    cargo bench --bench example
    tar -zcf benchmarks.tar.gz /cargo/target/criterion
timeout: 3600s
options:
  env:
    - RUSTC_WRAPPER=sccache
    - CMAKE_C_COMPILER_LAUNCHER=sccache
    - CMAKE_CXX_COMPILER_LAUNCHER=sccache
    - SCCACHE_GCS_BUCKET=zeedb-build-cache
    - SCCACHE_GCS_OAUTH_URL=http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/697461006037@cloudbuild.gserviceaccount.com/token
    - SCCACHE_GCS_RW_MODE=READ_WRITE
    - CARGO_INCREMENTAL=0
    - CARGO_HOME=/cargo/cache
    - CARGO_TARGET_DIR=/cargo/target
    - NO_RUSTFMT=1
    - RUST_BACKTRACE=1
    - LLVM_PROFILE_FILE=coverage-%p-%m.profraw
  volumes: 
    - name: cargo
      path: /cargo
  machineType: E2_HIGHCPU_8