steps:
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Build Tests'
    entrypoint: sh
    args: [-c, 'cargo test -Z timings --no-run && sccache --show-stats && cp cargo-timing.html cargo-timing-test.html']
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Run Tests'
    entrypoint: sh
    args: [-c, 'zetasql_server & cargo test']
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Build Benchmarks'
    entrypoint: sh
    args: [-c, 'cargo bench -Z timings --no-run && sccache --show-stats && cp cargo-timing.html cargo-timing-bench.html']
  - name: gcr.io/cloud-builders/gsutil
    id: 'Restore Benchmarks Timing'
    entrypoint: sh
    args: [-c, 'gsutil cp gs://zeedb-build-cache/criterion-${_RELEASE}.zip /cargo/target/criterion.zip && unzip /cargo/target/criterion.zip || true']
  - name: gcr.io/zeedeebee/zeedb-builder
    id: 'Run Benchmarks'
    entrypoint: sh
    args: [-c, 'zetasql_server & cargo bench -Z timings -p benchmarks && tar -zcf benchmarks.tar.gz /cargo/target/criterion']
  - name: gcr.io/cloud-builders/gsutil
    id: 'Save Benchmarks Timing'
    entrypoint: sh
    args: [-c, "find /cargo/target/criterion -name '*.json' | zip /cargo/target/criterion.zip -@ && gsutil cp /cargo/target/criterion.zip gs://zeedb-build-cache/criterion-${_DEVELOP}.zip"]
artifacts:
  objects:
    location: gs://zeedb-build-artifacts
    paths:
      - cargo-timing-test.html
      - cargo-timing-bench.html
      - benchmarks.tar.gz
substitutions: 
  _RELEASE: '1'
  _DEVELOP: '1'
options:
  env:
    - RUSTC_WRAPPER=sccache
    - CMAKE_C_COMPILER_LAUNCHER=sccache
    - CMAKE_CXX_COMPILER_LAUNCHER=sccache
    - SCCACHE_GCS_BUCKET=zeedb-build-cache
    - SCCACHE_GCS_OAUTH_URL=http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/697461006037@cloudbuild.gserviceaccount.com/token
    - SCCACHE_GCS_RW_MODE=READ_WRITE
    - CARGO_INCREMENTAL=0
    - CARGO_BUILD_TARGET=x86_64-unknown-linux-gnu
    - CARGO_HOME=/cargo/cache
    - CARGO_TARGET_DIR=/cargo/target
    - NO_RUSTFMT=1
    - RUST_BACKTRACE=1
  volumes: 
    - name: cargo
      path: /cargo
  machineType: E2_HIGHCPU_8
timeout: 3600s