FROM rust

RUN rustup toolchain install nightly-2021-05-10 && \
    rustup default nightly-2021-05-10

ENV SCCACHE_VERSION="v0.2.16-fork-5"
RUN wget -qO- "https://github.com/zeedb/sccache/releases/download/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar --strip-components=1 -xz -C /usr/local/bin && \
    chmod +x /usr/local/bin/sccache

RUN cargo search
RUN cargo install flamegraph