[package]
name = "ast"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
chrono = { version = "0.4.11" }
kernel = { path = "../kernel" }
zetasql = { path = "../zetasql" }