[package]
name = "storage"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
regex = "1.4.2"
twox-hash = "1.6.0"
catalog = { path = "../catalog" }
kernel = { path = "../kernel" }
sketch = { path = "../sketch" }

[dev-dependencies]
rand = "0.7.3"