[package]
name = "parser"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
chrono = "0.4.11"
futures = "0.3.13"
grpcio = { version = "0.8.2", default-features = false, features = ["prost-codec"]}
prost = "0.7.0"
prost-types = "0.7.0"
time = "0.1.39"
regex = "1.4.2"

ast = { path = "../ast" }
catalog_types = { path = "../catalog_types" }
context = { path = "../context" }
encoding = { path = "../encoding" }
kernel = { path = "../kernel" }
protos = { path = "../protos" }
zetasql = { path = "../zetasql" }

[dev-dependencies]
test_fixtures = { path = "../test_fixtures" }