[package]
name = "parser"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
ast = { path = "../ast" }
chrono = "0.4.11"
futures = "0.3.12"
once_cell = "1.5.2"
prost = "0.7.0"
prost-types = "0.7.0"
time = "0.1.39"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.4.0"
regex = "1.4.2"
catalog = { path = "../catalog" }
encoding = { path = "../encoding" }
kernel = { path = "../kernel" }
zetasql = { path = "../zetasql" }

[dev-dependencies]
test_fixtures = { path = "../test_fixtures" }