[package]
name = "coordinator"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.3.1"
futures = { version = "0.3.13", features = ["executor"] }
tokio = { version = "1.5.0", features = ["rt"] }
tonic = "0.4.3"
prost = "0.7"
prost-types = "0.7"
rand = { version = "0.8.2", features = ["small_rng"] }
rayon = "1.5"

ast = { path = "../ast" }
catalog = { path = "../catalog" }
catalog_types = { path = "../catalog_types" }
context = { path = "../context" }
parser = { path = "../parser" }
planner = { path = "../planner" }
protos = { path = "../protos" }
remote_execution = { path = "../remote_execution" }
statistics = { path = "../statistics" }
kernel = { path = "../kernel" }

[dev-dependencies]
worker = { path = "../worker" }