[package]
name = "encoding"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
bincode = "1.2.1"
chrono = { version = "0.4.11", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
zetasql = { path = "../zetasql" }