[package]
name = "storage"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
arrow = "2.0.0"
packed_simd = { version = "0.3.4", package = "packed_simd_2" }
rand = "0.7.3"
regex = "1.4.2"
ast = { path = "../ast" }
catalog = { path = "../catalog" }