[package]
name = "execute"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
chrono = "0.4.11"
num-traits = "0.2.14"
once_cell = "1.5.2"
rand = { version = "0.8.2", features = ["small_rng"]}
regex = "1.4.2"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.4.0"
ast = { path = "../ast" }
catalog = { path = "../catalog" }
context = { path = "../context" }
kernel = { path = "../kernel" }
parser = { path = "../parser" }
planner = { path = "../planner" }
protos = { path = "../protos" }
statistics = { path = "../statistics" }
storage = { path = "../storage" }
zetasql = { path = "../zetasql" }

[dev-dependencies]
test_fixtures = { path = "../test_fixtures" }