[package]
name = "worker"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "worker"
path = "main.rs"

[dependencies]
prost = "0.7"
prost-types = "0.7"
tokio = { version = "1.0.2", features = ["macros", "rt-multi-thread"] }
tonic = "0.4.0"
execute = { path = "../execute" }
protos = { path = "../protos" }