[package]
name = "benchmarks"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.11"
futures = { version = "0.3.13", features = ["executor"] }
grpcio = { version = "0.8.2", default-features = false, features = ["prost-codec"] }
rand = { version = "0.8.2", features = ["small_rng"]}

coordinator = { path = "../coordinator" }
protos = { path = "../protos" }
worker = { path = "../worker" }

[[bin]]
name = "benchmarks"
path = "main.rs"