[package]
name = "node"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
path = "lib.rs"

[dependencies]
chrono = "0.4"
decimal = "2.0.4"
encoding = { path = "../encoding" }
zetasql = { path = "../zetasql" }