name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Switch to nightly
      run: rustup default nightly
    - name: Update rust toolchain
      run: rustup update
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build
    - name: Run tests
      env: 
        RUST_BACKTRACE: 1
      run: cargo test --package e2e_tests --lib -- execute_tests::test_ddl --exact --nocapture
